/** Stable diagnostics emitted by generated-binding Runtime startup and execution. */
export const RuntimeDiagnosticCode = Object.freeze({
  INVALID_APPLICATION_BINDINGS: "RUNTIME1001_INVALID_APPLICATION_BINDINGS",
  DUPLICATE_BINDING_ID: "RUNTIME1002_DUPLICATE_BINDING_ID",
  PROVIDER_NOT_FOUND: "RUNTIME1003_PROVIDER_NOT_FOUND",
  PROVIDER_SCOPE_VIOLATION: "RUNTIME1004_PROVIDER_SCOPE_VIOLATION",
  PROVIDER_FACTORY_FAILED: "RUNTIME1005_PROVIDER_FACTORY_FAILED",
  CONTROLLER_FACTORY_FAILED: "RUNTIME1006_CONTROLLER_FACTORY_FAILED",
  HANDLER_BINDING_INVALID: "RUNTIME1007_HANDLER_BINDING_INVALID",
  GUARD_RESULT_INVALID: "RUNTIME1008_GUARD_RESULT_INVALID",
  TRANSPORT_LAUNCHER_MISSING: "RUNTIME1009_TRANSPORT_LAUNCHER_MISSING",
  TRANSPORT_START_FAILED: "RUNTIME1010_TRANSPORT_START_FAILED",
  INVALID_STATE_TRANSITION: "RUNTIME1011_INVALID_STATE_TRANSITION",
  SHUTDOWN_FAILED: "RUNTIME1012_SHUTDOWN_FAILED",
} as const);
