import { mkdir, readdir, unlink } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import type { BindingImport, ExecutableBindingPlan } from "../bindings";
import type { GeneratedApplication, OptimizedApplication } from "../output/artifact-types";

/** Generates deterministic executable TypeScript artifacts from optimized tables. */
export function generateArtifacts(optimized: OptimizedApplication, bindings?: ExecutableBindingPlan): GeneratedApplication {
  const files: Record<string, string> = {
    "tables.generated.ts": tablesSource(optimized),
    "routes.generated.ts": routesSource(optimized),
    "socket.generated.ts": socketSource(optimized),
    "providers.generated.ts": bindings === undefined ? providersSource() : executableProvidersSource(bindings),
  };
  if (bindings !== undefined) {
    if (bindings.controllers.length > 0) files["controllers.generated.ts"] = controllersSource(bindings);
    if (bindings.handlers.length > 0) files["handlers.generated.ts"] = handlersSource(bindings);
    if (bindings.guards.length > 0) files["guards.generated.ts"] = executableValuesSource("guardBindings", "execute", bindings.guards);
    if (bindings.middlewares.length > 0) files["middleware.generated.ts"] = executableValuesSource("middlewareBindings", "execute", bindings.middlewares);
    if (bindings.validators.length > 0) files["validators.generated.ts"] = validatorsSource(bindings.validators);
    if (optimized.routes.length > 0) files["http.generated.ts"] = httpBindingsSource(optimized);
    if (optimized.socketEvents.length > 0) files["websocket.generated.ts"] = websocketBindingsSource(optimized);
    files["bindings.generated.ts"] = bindingsSource(bindings, optimized);
    files["production.generated.ts"] = productionSource();
  }
  files["application.generated.ts"] = applicationSource(bindings, optimized);
  return Object.freeze({ optimized, ...(bindings === undefined ? {} : { bindings }), files: Object.freeze(files) });
}

/** Writes generated artifacts in stable filename order. */
export interface DevelopmentArtifactSnapshot {
  readonly fingerprint: string;
  readonly sources: readonly Readonly<{ file: string; text: string }>[];
}
export async function writeArtifacts(projectRoot: string, generated: GeneratedApplication, snapshot?: DevelopmentArtifactSnapshot): Promise<void> {
  const outputDirectory = `${projectRoot}/.warbler/generated`;
  await mkdir(outputDirectory, { recursive: true });
  const current = new Set(Object.keys(generated.files));
  for (const name of await readdir(outputDirectory)) {
    if (name.endsWith(".generated.ts") && !current.has(name)) await unlink(`${outputDirectory}/${name}`);
  }
  for (const name of Object.keys(generated.files).sort()) await Bun.write(`${outputDirectory}/${name}`, generated.files[name]!);
  if (snapshot !== undefined) {
    const snapshotDirectory = `${outputDirectory}/build-${snapshot.fingerprint}`;
    await mkdir(snapshotDirectory, { recursive: true });
    for (const source of snapshot.sources) {
      const relativeSource = relative(projectRoot, source.file).replaceAll("\\", "/");
      const destination = `${snapshotDirectory}/source/${relativeSource}`;
      await mkdir(dirname(destination), { recursive: true });
      await Bun.write(destination, source.text);
    }
    for (const name of Object.keys(generated.files).sort()) {
      await Bun.write(`${snapshotDirectory}/${name}`, snapshotGeneratedSource(generated.files[name]!, outputDirectory, projectRoot));
    }
  }
}
function snapshotGeneratedSource(source: string, generatedDirectory: string, projectRoot: string): string {
  return source.replace(/from ("[^"]+"|'[^']+')/gu, (match, quoted: string) => {
    const module = quoted.slice(1, -1);
    if (!module.startsWith("../")) return match;
    const absolute = resolve(generatedDirectory, module);
    const projectRelative = relative(projectRoot, absolute).replaceAll("\\", "/");
    return `from ${JSON.stringify(`./source/${projectRelative}`)}`;
  });
}

function tablesSource(value: OptimizedApplication): string {
  return `/* Generated by @warbler/compiler. Do not edit. */
export const strings = ${frozenPrimitiveArray(value.strings)};
export const graphIds = Object.freeze(${JSON.stringify(value.graphIds)});
export const providerTable = ${frozenRows(value.providers)};
export const providerDependencies = ${frozenPrimitiveArray(value.providerDependencies)};
export const controllerTable = ${frozenRows(value.controllers)};
export const routeTable = ${frozenRows(value.routes)};
export const socketEventTable = ${frozenRows(value.socketEvents)};
export const handlerTable = ${frozenRows(value.handlers)};
export const validatorTable = ${frozenRows(value.validators)};
export const middlewareTable = ${frozenRows(value.middlewares)};
export const guardTable = ${frozenRows(value.guards)};
export const routeMiddleware = ${frozenPrimitiveArray(value.routeMiddleware)};
export const routeGuards = ${frozenPrimitiveArray(value.routeGuards)};
export const socketMiddleware = ${frozenPrimitiveArray(value.socketMiddleware)};
export const socketGuards = ${frozenPrimitiveArray(value.socketGuards)};
`;
}
function routesSource(value: OptimizedApplication): string {
  const groups = new Map<number, typeof value.routes[number][]>();
  for (const route of value.routes) {
    const current = groups.get(route.pathId) ?? [];
    current.push(route);
    groups.set(route.pathId, current);
  }
  const paths = [...groups.entries()].sort((left, right) => left[0] - right[0]).map(([pathId, routes]) => {
    const methods = routes.map((route) => `      [strings[${route.methodId}]!]: handlers[${route.handlerId}]!,`).join("\n");
    return `    [strings[${pathId}]!]: Object.freeze({\n${methods}\n    }),`;
  }).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import { routeTable, strings } from "./tables.generated";
export type GeneratedRouteHandler = (request: Request) => Response | Promise<Response>;
export type GeneratedRoutes = Readonly<Record<string, Readonly<Record<string, GeneratedRouteHandler>>>>;
export function createRoutes(handlers: readonly GeneratedRouteHandler[]): GeneratedRoutes {
  if (handlers.length < ${value.handlers.length}) throw new RangeError("Missing generated route handlers.");
  return Object.freeze({
${paths}
  });
}
export const routeLookup = Object.freeze(Object.fromEntries(
  routeTable.map((route) => [\`\${strings[route.methodId]} \${strings[route.pathId]}\`, route.id]),
)) as Readonly<Record<string, number>>;
`;
}
function socketSource(value: OptimizedApplication): string {
  const groups = new Map<number, typeof value.socketEvents[number][]>();
  const lifecycleGroups = new Map<number, typeof value.socketEvents[number][]>();
  for (const event of value.socketEvents) {
    const target = event.lifecycle ? lifecycleGroups : groups;
    const current = target.get(event.controllerId) ?? [];
    current.push(event);
    target.set(event.controllerId, current);
  }
  const render = (source: ReadonlyMap<number, readonly typeof value.socketEvents[number][]>) => [...source.entries()].sort((left, right) => left[0] - right[0]).map(([controllerId, events]) => {
    const rows = events.map((event) => `      [strings[${event.eventId}]!]: handlers[${event.handlerId}]!,`).join("\n");
    return `    ${JSON.stringify(controllerId)}: Object.freeze({\n${rows}\n    }),`;
  }).join("\n");
  const controllers = render(groups);
  const lifecycles = render(lifecycleGroups);
  return `/* Generated by @warbler/compiler. Do not edit. */
import { strings } from "./tables.generated";
export type GeneratedSocketHandler = (message: unknown, context: unknown) => unknown;
export type GeneratedSocketDispatchers = Readonly<Record<number, Readonly<Record<string, GeneratedSocketHandler>>>>;
export function createSocketDispatchers(handlers: readonly GeneratedSocketHandler[]): GeneratedSocketDispatchers {
  if (handlers.length < ${value.handlers.length}) throw new RangeError("Missing generated socket handlers.");
  return Object.freeze({
${controllers}
  });
}
export function createSocketLifecycleHandlers(handlers: readonly GeneratedSocketHandler[]): GeneratedSocketDispatchers {
  if (handlers.length < ${value.handlers.length}) throw new RangeError("Missing generated socket handlers.");
  return Object.freeze({
${lifecycles}
  });
}
`;
}
function providersSource(): string {
  return `/* Generated by @warbler/compiler. Do not edit. */
import { providerDependencies, providerTable } from "./tables.generated";
export type GeneratedProviderFactory = (dependencies: readonly unknown[]) => unknown;
export interface GeneratedProviderResolver { resolve(providerId: number): unknown }
export function createProviderResolver(factories: readonly GeneratedProviderFactory[]): GeneratedProviderResolver {
  const instances: unknown[] = [];
  const created: boolean[] = [];
  const resolving = new Set<number>();
  const resolve = (providerId: number): unknown => {
    if (created[providerId]) return instances[providerId];
    const provider = providerTable[providerId];
    const factory = factories[providerId];
    if (provider === undefined || factory === undefined) throw new RangeError(\`Unknown generated provider: \${providerId}\`);
    if (resolving.has(providerId)) throw new Error(\`Generated provider cycle: \${providerId}\`);
    resolving.add(providerId);
    try {
      const dependencies = providerDependencies
        .slice(provider.dependencyStart, provider.dependencyStart + provider.dependencyCount)
        .map(resolve);
      const instance = factory(dependencies);
      instances[providerId] = instance;
      created[providerId] = true;
      return instance;
    } finally {
      resolving.delete(providerId);
    }
  };
  return Object.freeze({ resolve });
}
`;
}
function applicationSource(bindings: ExecutableBindingPlan | undefined, _optimized: OptimizedApplication): string {
  if (bindings !== undefined) {
    return `/* Generated by @warbler/compiler. Do not edit. */
export { applicationBindings as default, applicationBindings } from "./bindings.generated";
export * from "./bindings.generated";
`;
  }
  return `/* Generated by @warbler/compiler. Do not edit. */
export * from "./tables.generated";
export * from "./routes.generated";
export * from "./socket.generated";
export * from "./providers.generated";
`;
}
function frozenPrimitiveArray(values: readonly unknown[]): string { return `Object.freeze(${JSON.stringify(values)})`; }
function frozenRows(values: readonly object[]): string {
  return `Object.freeze([${values.map((value) => `Object.freeze(${JSON.stringify(value)})`).join(",")}])`;
}

function executableProvidersSource(bindings: ExecutableBindingPlan): string {
  const imports = renderImports(bindings.providers.flatMap((binding) => [binding.symbol, ...binding.dependencySymbols]));
  const rows = bindings.providers.map((binding) => `  Object.freeze({
    id: ${binding.id},
    token: ${binding.symbol.local},
    scope: ${JSON.stringify(binding.scope)},
    ${binding.scope === "graph" ? `graphId: ${binding.graphId},\n    ` : ""}dependencyIds: Object.freeze(${JSON.stringify(binding.dependencyIds)}),
    factory: (context: ProviderBindingContext) => context.run(() => new ${binding.symbol.local}()),
  }),`).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import type { ProviderBinding, ProviderBindingContext } from "@warbler/runtime";
${imports}
export const providerBindings = Object.freeze([
${rows}
]) satisfies readonly ProviderBinding[];
${providersSource().replace("/* Generated by @warbler/compiler. Do not edit. */\n", "")}`;
}
function controllersSource(bindings: ExecutableBindingPlan): string {
  const imports = renderImports(bindings.controllers.map((binding) => binding.symbol));
  const rows = bindings.controllers.map((binding) => `  Object.freeze({
    id: ${binding.id}, graphId: ${binding.graphId}, transport: ${JSON.stringify(binding.transport)},
    token: ${binding.symbol.local},
    factory: (context: ProviderBindingContext) => context.run(() => new ${binding.symbol.local}()),
  }),`).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import type { ControllerBinding, ProviderBindingContext } from "@warbler/runtime";
${imports}
export const controllerBindings = Object.freeze([
${rows}
]) satisfies readonly ControllerBinding[];
`;
}
function handlersSource(bindings: ExecutableBindingPlan): string {
  const imports = renderImports(bindings.handlers.map((binding) => binding.controller));
  const functions = bindings.handlers.map((binding) => `const invokeHandler${binding.id} = (
  controller: InstanceType<typeof ${binding.controller.local}>,
  ...input: Parameters<InstanceType<typeof ${binding.controller.local}>[${JSON.stringify(binding.method)}]>
): ReturnType<InstanceType<typeof ${binding.controller.local}>[${JSON.stringify(binding.method)}]> =>
  controller.${binding.method}(...input);
`).join("\n");
  const rows = bindings.handlers.map((binding) => `  Object.freeze({ id: ${binding.id}, controllerId: ${binding.controllerId}, invoke: invokeHandler${binding.id} }),`).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import type { HandlerBinding } from "@warbler/runtime";
${imports}
${functions}
export const handlerBindings = Object.freeze([
${rows}
]) satisfies readonly HandlerBinding[];
`;
}
function executableValuesSource(table: string, property: string, bindings: readonly (BindingImport & { readonly id: number })[]): string {
  return `/* Generated by @warbler/compiler. Do not edit. */
${renderImports(bindings)}
export const ${table} = Object.freeze([
${bindings.map((binding) => `  Object.freeze({ id: ${binding.id}, ${property}: ${binding.local} }),`).join("\n")}
]);
`;
}
function validatorsSource(bindings: readonly (BindingImport & { readonly id: number })[]): string {
  const compiled = bindings.map((binding) => `const CompiledValidator${binding.id} = compileValidator(${binding.local}, ${binding.id});`).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import { compileValidator } from "@warbler/validators";
${renderImports(bindings)}
${compiled}
export const validatorBindings = Object.freeze([
${bindings.map((binding) => `  Object.freeze({ id: ${binding.id}, flags: CompiledValidator${binding.id}.flags, validate: CompiledValidator${binding.id}.execute }),`).join("\n")}
]);
`;
}
function httpBindingsSource(optimized: OptimizedApplication): string {
  const rows = optimized.routes.map((route) => `  Object.freeze(${JSON.stringify(route)}),`).join("\n");
  const paths = [...new Set(optimized.routes.map((route) => route.pathId))].sort((a, b) => a - b).map((pathId) => {
    const methods = optimized.routes.filter((route) => route.pathId === pathId).map((route) =>
      route.validatorId < 0
        ? `    [strings[${route.methodId}]!]: (request: Request) => executeHttpRoute(${route.id}, request),`
        : `    [strings[${route.methodId}]!]: (request: Request) => prepareHttpValidationInput(request, validatorBindings[${route.validatorId}]!.flags).then((input) => executeHttpRoute(${route.id}, request, input)),`,
    ).join("\n");
    return `  [strings[${pathId}]!]: Object.freeze({\n${methods}\n  }),`;
  }).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import type { HttpRouteExecutor } from "@warbler/runtime";
import { prepareHttpValidationInput } from "@warbler/http";
${optimized.routes.some((route) => route.validatorId >= 0) ? `import { validatorBindings } from "./validators.generated";` : ""}
import { strings } from "./tables.generated";
export const httpRouteBindings = Object.freeze([
${rows}
]);
export const createHttpRoutes = (executeHttpRoute: HttpRouteExecutor) => Object.freeze({
${paths}
});
`;
}
function websocketBindingsSource(optimized: OptimizedApplication): string {
  const entries = optimized.socketEvents.map((event) =>
    `  [strings[${event.eventId}]!]: Object.freeze(${JSON.stringify(event)}),`,
  ).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import { strings } from "./tables.generated";
export const socketEventBindings = Object.freeze({
${entries}
});
export const unknownSocketEvent = undefined;
`;
}
function bindingsSource(bindings: ExecutableBindingPlan, optimized: OptimizedApplication): string {
  const imports = [
    `import { strings, graphIds, providerTable, providerDependencies, routeTable, socketEventTable, routeGuards, routeMiddleware, socketGuards, socketMiddleware } from "./tables.generated";`,
    bindings.providers.length > 0 ? `import { providerBindings } from "./providers.generated";` : "",
    bindings.controllers.length > 0 ? `import { controllerBindings } from "./controllers.generated";` : "",
    bindings.handlers.length > 0 ? `import { handlerBindings } from "./handlers.generated";` : "",
    bindings.guards.length > 0 ? `import { guardBindings } from "./guards.generated";` : "",
    bindings.middlewares.length > 0 ? `import { middlewareBindings } from "./middleware.generated";` : "",
    bindings.validators.length > 0 ? `import { validatorBindings } from "./validators.generated";` : "",
    optimized.routes.length > 0 ? `import { createHttpRoutes, httpRouteBindings } from "./http.generated";` : "",
    optimized.socketEvents.length > 0 ? `import { socketEventBindings } from "./websocket.generated";` : "",
  ].filter(Boolean).join("\n");
  return `/* Generated by @warbler/compiler. Do not edit. */
import type { GeneratedApplicationBindings } from "@warbler/runtime";
${imports}
export const applicationBindings = Object.freeze({
  application: Object.freeze({
    strings, graphIds, providerTable, providerDependencies, routeTable, socketEventTable,
    routeGuards, routeMiddleware, socketGuards, socketMiddleware,
  }),
  providers: ${bindings.providers.length > 0 ? "providerBindings" : "Object.freeze([])"},
  controllers: ${bindings.controllers.length > 0 ? "controllerBindings" : "Object.freeze([])"},
  handlers: ${bindings.handlers.length > 0 ? "handlerBindings" : "Object.freeze([])"},
  guards: ${bindings.guards.length > 0 ? "guardBindings" : "Object.freeze([])"},
  middleware: ${bindings.middlewares.length > 0 ? "middlewareBindings" : "Object.freeze([])"},
  validators: ${bindings.validators.length > 0 ? "validatorBindings" : "Object.freeze([])"},
  ${optimized.routes.length > 0 ? "http: Object.freeze({ routes: httpRouteBindings, createRoutes: createHttpRoutes })," : ""}
  ${optimized.socketEvents.length > 0 ? "websocket: Object.freeze({ events: socketEventBindings })," : ""}
}) satisfies GeneratedApplicationBindings;
export default applicationBindings;
`;
}
function productionSource(): string {
  return `/* Generated by @warbler/compiler. Do not edit. */
import { createExecutableBindingsRuntime, type ExecutableBindingsRuntime, type GeneratedApplicationBindings } from "@warbler/runtime";
import applicationBindings from "./application.generated";
export type GeneratedRuntimeLauncher<T = ExecutableBindingsRuntime> = (bindings: GeneratedApplicationBindings) => T | Promise<T>;
export const startGeneratedApplication = <T = ExecutableBindingsRuntime>(
  launcher: GeneratedRuntimeLauncher<T> = createExecutableBindingsRuntime as GeneratedRuntimeLauncher<T>,
): T | Promise<T> => launcher(applicationBindings);
const runtime = startGeneratedApplication();
export default runtime;
`;
}
function renderImports(values: readonly BindingImport[]): string {
  const unique = [...new Map(values.map((value) => [`${value.module}:${value.imported}`, value])).values()]
    .sort((left, right) => compareText(left.module, right.module) || compareText(left.imported, right.imported));
  return unique.map((value) => value.kind === "default"
    ? `import ${value.local} from ${JSON.stringify(value.module)};`
    : `import { ${value.imported} as ${value.local} } from ${JSON.stringify(value.module)};`
  ).join("\n");
}
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
