import type { ColumnMetadata, EnumTypeMetadata, TableMetadata } from "../types/model.types";
import { quoteIdentifier, quoteLiteral } from "../utils/sql-identifier";
import {
  renderCheckConstraint,
  renderColumnDefinition,
  renderCreateEnumStatement,
  renderCreateIndexStatement,
  renderForeignKeyConstraint,
} from "./ddl-fragments";

const compareText = (left: string, right: string): number => (left < right ? -1 : left > right ? 1 : 0);

function renderColumn(column: ColumnMetadata): string {
  return `  ${renderColumnDefinition(column)}`;
}

function renderTable(table: TableMetadata): string {
  const lines = table.columns.map(renderColumn);

  if (table.primaryKey.length > 0) {
    lines.push(`  PRIMARY KEY (${table.primaryKey.map(quoteIdentifier).join(", ")})`);
  }
  for (const check of table.checks) lines.push(`  ${renderCheckConstraint(table.tableName, check)}`);
  for (const foreignKey of table.foreignKeys) lines.push(`  ${renderForeignKeyConstraint(table.tableName, foreignKey)}`);

  const statements = [`CREATE TABLE ${quoteIdentifier(table.tableName)} (\n${lines.join(",\n")}\n);`];

  for (const index of table.indexes) {
    statements.push(renderCreateIndexStatement(table.tableName, index.name, [index.column], index.unique));
  }

  for (const column of table.columns) {
    if (column.comment === undefined) continue;
    statements.push(
      `COMMENT ON COLUMN ${quoteIdentifier(table.tableName)}.${quoteIdentifier(column.columnName)} IS ${quoteLiteral(column.comment)};`,
    );
  }

  return statements.join("\n");
}

/** Produces deterministic `schema.sql` text: enum types, then tables sorted by name. A read-only mirror of the live introspected schema, not an input. */
export function generateSchemaSql(tables: readonly TableMetadata[]): string {
  const enums = new Map<string, EnumTypeMetadata>();
  for (const table of tables) {
    for (const enumType of table.enums) enums.set(enumType.name, enumType);
  }

  const sortedTables = [...tables].sort((left, right) => compareText(left.tableName, right.tableName));
  const sortedEnums = [...enums.values()].sort((left, right) => compareText(left.name, right.name));

  const sections = [
    "-- Generated by @warbler/database. Do not edit by hand.",
    ...sortedEnums.map((enumType) => renderCreateEnumStatement(enumType.name, enumType.values)),
    ...sortedTables.map(renderTable),
  ];

  return `${sections.join("\n\n")}\n`;
}
