import { getCryptoConfig } from "../config";
import { encodeBytes, type EncodingName } from "../encoding";
import { RandomError } from "../errors";

const HARD_MAX_BYTES = 1024 * 1024;

/** Options for random byte and token generation. */
export interface RandomOptions {
  readonly output?: EncodingName;
}

function assertLength(length: number, maxBytes = HARD_MAX_BYTES): number {
  if (!Number.isSafeInteger(length) || length <= 0) {
    throw new RandomError("Random byte length must be a positive safe integer.");
  }
  if (length > maxBytes || length > HARD_MAX_BYTES) {
    throw new RandomError("Random byte length cannot exceed 1048576 bytes.");
  }
  return length;
}

/** Returns cryptographically secure random bytes. */
export function bytes(length: number): Uint8Array<ArrayBuffer> {
  const output = new Uint8Array(new ArrayBuffer(assertLength(length)));
  crypto.getRandomValues(output);
  return output;
}

/** Returns cryptographically secure random bytes encoded as hexadecimal text. */
export function hex(length: number): string {
  return encodeBytes(bytes(length), "hex");
}

/** Returns cryptographically secure random bytes encoded as base64 text. */
export function base64(length: number): string {
  return encodeBytes(bytes(length), "base64");
}

/** Returns cryptographically secure random bytes encoded as base64url text. */
export function base64url(length: number): string {
  return encodeBytes(bytes(length), "base64url");
}

/** Returns a cryptographically secure token using configured defaults unless overridden. */
export async function token(length?: number, options: RandomOptions = {}): Promise<string> {
  const config = await getCryptoConfig();
  const size = assertLength(length ?? config.random.tokenBytes, config.random.maxBytes);
  return encodeBytes(bytes(size), options.output ?? config.encoding.output);
}

/** Returns a random RFC 4122 UUID generated by the Web Crypto runtime. */
export function uuid(): string {
  return crypto.randomUUID();
}

/** Random generation helpers backed by Web Crypto. */
export const random = Object.freeze({
  base64,
  base64url,
  bytes,
  hex,
  token,
  uuid,
});
