import type { DatabaseProjectConfig } from "../types/config.types";

function relativeConfigImport(config: DatabaseProjectConfig): string {
  const depth = config.migrations.generated.split("/").filter((segment) => segment.length > 0).length + 1; // + "runtime"
  return `${"../".repeat(depth)}src/config/database.config`;
}

/** Generates `runtime/pg-client.ts`: the one place a live Bun `SQL` connection is constructed. */
export function generateRuntimeClientSource(config: DatabaseProjectConfig): string {
  const configImport = relativeConfigImport(config);
  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    'import { createPgConnection } from "@warbler/database";',
    `import { databaseConfig } from ${JSON.stringify(configImport)};`,
    "",
    "export const pg = createPgConnection(databaseConfig.pg.connection);",
    "",
  ].join("\n");
}
