import { DatabaseCompileError } from "../errors";
import type { ColumnMetadata, TableMetadata } from "../types/model.types";

const SERIAL_TYPES = new Set(["smallserial", "serial", "bigserial"]);

function isAutoGenerated(column: ColumnMetadata): boolean {
  return column.identity || SERIAL_TYPES.has(column.pgType);
}

function isOptionalForInsert(column: ColumnMetadata): boolean {
  return column.nullable || column.default !== undefined || isAutoGenerated(column);
}

function baseTsType(column: ColumnMetadata): string {
  switch (column.pgType) {
    case "boolean":
      return "boolean";
    case "smallint":
    case "integer":
    case "smallserial":
    case "serial":
    case "real":
    case "double precision":
      return "number";
    case "bigint":
    case "bigserial":
    case "numeric":
    case "money":
      return "string";
    case "bytea":
      return "Uint8Array";
    case "json":
    case "jsonb":
      return "unknown";
    case "date":
    case "timestamp":
    case "timestamptz":
      return "Date";
    default:
      return "string";
  }
}

function tsType(column: ColumnMetadata): string {
  const base = baseTsType(column);
  const shape = column.sqlType.endsWith("[]") ? `readonly ${base}[]` : base;
  return column.nullable ? `${shape} | null` : shape;
}

function pascalCase(modelName: string): string {
  return modelName.charAt(0).toUpperCase() + modelName.slice(1);
}

function rowInterface(table: TableMetadata, typeName: string): string {
  const fields = table.columns.map((column) => `  ${column.fieldName}: ${tsType(column)};`);
  return [`export interface ${typeName} {`, ...fields, "}"].join("\n");
}

function insertInterface(typeName: string, insertable: readonly ColumnMetadata[]): string {
  const fields = insertable.map((column) => `  ${column.fieldName}${isOptionalForInsert(column) ? "?" : ""}: ${tsType(column)};`);
  return [`export interface ${typeName} {`, ...fields, "}"].join("\n");
}

function updateInterface(typeName: string, updatable: readonly ColumnMetadata[]): string {
  const fields: string[] = new Array(updatable.length);
  for (let i = 0; i < updatable.length; i++) {
    const column = updatable[i]!;
    fields[i] = `  ${column.fieldName}?: ${tsType(column)};`;
  }
  return [`export interface ${typeName} {`, ...fields, "}"].join("\n");
}

function whereInterface(typeName: string, columns: readonly ColumnMetadata[]): string {
  const fields: string[] = new Array(columns.length);
  for (let i = 0; i < columns.length; i++) {
    const column = columns[i]!;
    fields[i] = `  readonly ${column.fieldName}?: ${tsType(column)};`;
  }
  return [`export interface ${typeName} {`, ...fields, "}"].join("\n");
}

function uniqueWhereType(typeName: string, uniqueColumns: readonly ColumnMetadata[]): string {
  const variants = uniqueColumns.map((column) => `  | { readonly ${column.fieldName}: ${tsType(column)} }`);
  return [`export type ${typeName} =`, ...variants].join("\n") + ";";
}

function selectList(table: TableMetadata): string {
  return table.columns.map((column) => `"${column.columnName}" AS "${column.fieldName}"`).join(", ");
}

function orderColumn(table: TableMetadata): string {
  return table.primaryKey[0] ?? table.columns[0]?.columnName ?? "";
}

function uniqueBranch(
  column: ColumnMetadata,
  build: (accessor: string) => string,
): string {
  return [
    `    case "${column.fieldName}": {`,
    `      ${build(`input.${column.fieldName} as ${tsType(column)}`)}`,
    "    }",
  ].join("\n");
}

/** Generates the CRUD client source for a single model, as plain TypeScript source text. */
export function generateClientSource(table: TableMetadata): string {
  const uniqueColumns = table.columns.filter((column) => column.primaryKey || column.unique);
  if (uniqueColumns.length === 0) {
    throw new DatabaseCompileError(
      table.modelName,
      "At least one column must be marked `primaryKey` or `unique` to generate findUnique/update/delete.",
    );
  }

  const insertable = table.columns.filter((column) => !isAutoGenerated(column));
  const updatable = insertable.filter((column) => !column.primaryKey);

  const name = pascalCase(table.modelName);
  const rowType = `${name}Row`;
  const insertType = `${name}InsertInput`;
  const updateType = `${name}UpdateInput`;
  const updateManyType = `${name}UpdateManyInput`;
  const whereType = `${name}UniqueWhere`;
  const manyWhereType = `${name}Where`;

  const columns = selectList(table);
  const order = orderColumn(table);
  const tableIdentifier = `"${table.tableName}"`;

  const findUniqueBody = [
    "export async function findUnique(where: " + whereType + "): Promise<" + rowType + " | null> {",
    "  const input = where as Record<string, unknown>;",
    "  const key = Object.keys(input)[0];",
    "  switch (key) {",
    ...uniqueColumns.map((column) =>
      uniqueBranch(
        column,
        (accessor) =>
          `const [row] = await pg\`SELECT ${columns} FROM ${tableIdentifier} WHERE "${column.columnName}" = ${"$"}{${accessor}} LIMIT 1\`;\n      return (row as ${rowType} | undefined) ?? null;`,
      )
    ),
    "    default:",
    `      throw new Error("findUnique requires exactly one of: ${uniqueColumns.map((c) => c.fieldName).join(", ")}");`,
    "  }",
    "}",
  ].join("\n");

  const findFirstBody = [
    `export async function findFirst(where?: ${whereType}): Promise<${rowType} | null> {`,
    "  if (where === undefined) {",
    `    const [row] = await pg\`SELECT ${columns} FROM ${tableIdentifier} ORDER BY "${order}" LIMIT 1\`;`,
    `    return (row as ${rowType} | undefined) ?? null;`,
    "  }",
    "  return findUnique(where);",
    "}",
  ].join("\n");

  const findManyBody = [
    `export async function findMany(options: { readonly limit?: number; readonly offset?: number } = {}): Promise<${rowType}[]> {`,
    "  const limit = options.limit ?? 100;",
    "  const offset = options.offset ?? 0;",
    `  const rows = await pg\`SELECT ${columns} FROM ${tableIdentifier} ORDER BY "${order}" LIMIT ${"$"}{limit} OFFSET ${"$"}{offset}\`;`,
    `  return rows as unknown as ${rowType}[];`,
    "}",
  ].join("\n");

  const insertAssignments = insertable.map((column) => {
    const assign = `columns["${column.columnName}"] = data.${column.fieldName};`;
    return isOptionalForInsert(column)
      ? `  if (data.${column.fieldName} !== undefined) ${assign}`
      : `  ${assign}`;
  });
  const insertBody = [
    `export async function insert(data: ${insertType}): Promise<${rowType}> {`,
    "  const columns: Record<string, unknown> = {};",
    ...insertAssignments,
    `  const [row] = await pg\`INSERT INTO ${tableIdentifier} ${"$"}{pg(columns)} RETURNING ${columns}\`;`,
    `  return row as ${rowType};`,
    "}",
  ].join("\n");

  const updateAssignments = updatable.map((column) =>
    `  if (data.${column.fieldName} !== undefined) columns["${column.columnName}"] = data.${column.fieldName};`
  );
  const updateBody = [
    `export async function update(where: ${whereType}, data: ${updateType}): Promise<${rowType} | null> {`,
    "  const columns: Record<string, unknown> = {};",
    ...updateAssignments,
    "  if (Object.keys(columns).length === 0) return findUnique(where);",
    "  const input = where as Record<string, unknown>;",
    "  const key = Object.keys(input)[0];",
    "  switch (key) {",
    ...uniqueColumns.map((column) =>
      uniqueBranch(
        column,
        (accessor) =>
          `const [row] = await pg\`UPDATE ${tableIdentifier} SET ${"$"}{pg(columns)} WHERE "${column.columnName}" = ${"$"}{${accessor}} RETURNING ${columns}\`;\n      return (row as ${rowType} | undefined) ?? null;`,
      )
    ),
    "    default:",
    `      throw new Error("update requires exactly one of: ${uniqueColumns.map((c) => c.fieldName).join(", ")}");`,
    "  }",
    "}",
  ].join("\n");

  const updateManyAssignments: string[] = new Array(updatable.length);
  for (let i = 0; i < updatable.length; i++) {
    const column = updatable[i]!;
    updateManyAssignments[i] = `  if (data.${column.fieldName} !== undefined) columns["${column.columnName}"] = data.${column.fieldName};`;
  }

  const updateManyPredicates: string[] = new Array(table.columns.length);
  for (let i = 0; i < table.columns.length; i++) {
    const column = table.columns[i]!;
    const accessor = `where.${column.fieldName}`;
    if (column.nullable) {
      updateManyPredicates[i] = [
        `  if (${accessor} !== undefined) {`,
        `    const next = ${accessor} === null`,
        `      ? pg\`"${column.columnName}" IS NULL\``,
        `      : pg\`"${column.columnName}" = \${${accessor} as ${tsType(column)}}\`;`,
        "    predicate = hasWhere ? pg`${predicate} AND ${next}` : next;",
        "    hasWhere = true;",
        "  }",
      ].join("\n");
    } else {
      updateManyPredicates[i] = [
        `  if (${accessor} !== undefined) {`,
        `    const next = pg\`"${column.columnName}" = \${${accessor} as ${tsType(column)}}\`;`,
        "    predicate = hasWhere ? pg`${predicate} AND ${next}` : next;",
        "    hasWhere = true;",
        "  }",
      ].join("\n");
    }
  }

  const updateManyBody = [
    `export async function updateMany(where: ${manyWhereType}, data: ${updateManyType}): Promise<number> {`,
    "  const columns: Record<string, unknown> = {};",
    ...updateManyAssignments,
    "  if (Object.keys(columns).length === 0) {",
    '    throw new Error("updateMany requires at least one field to update");',
    "  }",
    "  let predicate = pg``;",
    "  let hasWhere = false;",
    ...updateManyPredicates,
    "  if (!hasWhere) {",
    '    throw new Error("updateMany requires at least one where condition");',
    "  }",
    `  const [row] = await pg\`WITH updated AS (UPDATE ${tableIdentifier} SET \${pg(columns)} WHERE \${predicate} RETURNING 1) SELECT count(*)::int AS "count" FROM updated\`;`,
    "  return (row as { count: number }).count;",
    "}",
  ].join("\n");

  const deleteBody = [
    `export async function deleteOne(where: ${whereType}): Promise<${rowType} | null> {`,
    "  const input = where as Record<string, unknown>;",
    "  const key = Object.keys(input)[0];",
    "  switch (key) {",
    ...uniqueColumns.map((column) =>
      uniqueBranch(
        column,
        (accessor) =>
          `const [row] = await pg\`DELETE FROM ${tableIdentifier} WHERE "${column.columnName}" = ${"$"}{${accessor}} RETURNING ${columns}\`;\n      return (row as ${rowType} | undefined) ?? null;`,
      )
    ),
    "    default:",
    `      throw new Error("delete requires exactly one of: ${uniqueColumns.map((c) => c.fieldName).join(", ")}");`,
    "  }",
    "}",
  ].join("\n");

  const countBody = [
    `export async function count(where?: ${whereType}): Promise<number> {`,
    "  if (where === undefined) {",
    `    const [row] = await pg\`SELECT count(*)::int AS "count" FROM ${tableIdentifier}\`;`,
    "    return (row as { count: number }).count;",
    "  }",
    "  const input = where as Record<string, unknown>;",
    "  const key = Object.keys(input)[0];",
    "  switch (key) {",
    ...uniqueColumns.map((column) =>
      uniqueBranch(
        column,
        (accessor) =>
          `const [row] = await pg\`SELECT count(*)::int AS "count" FROM ${tableIdentifier} WHERE "${column.columnName}" = ${"$"}{${accessor}}\`;\n      return (row as { count: number }).count;`,
      )
    ),
    "    default:",
    `      throw new Error("count requires exactly one of: ${uniqueColumns.map((c) => c.fieldName).join(", ")}");`,
    "  }",
    "}",
  ].join("\n");

  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    'import { pg } from "../runtime/pg-client";',
    "",
    rowInterface(table, rowType),
    "",
    insertInterface(insertType, insertable),
    "",
    updateInterface(updateType, updatable),
    "",
    updateInterface(updateManyType, updatable),
    "",
    uniqueWhereType(whereType, uniqueColumns),
    "",
    whereInterface(manyWhereType, table.columns),
    "",
    findUniqueBody,
    "",
    findFirstBody,
    "",
    findManyBody,
    "",
    insertBody,
    "",
    updateBody,
    "",
    updateManyBody,
    "",
    deleteBody,
    "",
    countBody,
    "",
  ].join("\n");
}

/** Generates `client/index.ts`: imports every per-model module and assembles `WlbPg`. */
export function generateClientBarrelSource(tables: readonly TableMetadata[]): string {
  const modules = tableModules(tables);
  const imports = modules.map((entry) => `import * as ${entry.namespace} from "./${entry.fileName}";`);
  const entries = modules.map((entry) =>
    [
      `  ${entry.clientKey}: {`,
      `    findUnique: ${entry.namespace}.findUnique,`,
      `    findFirst: ${entry.namespace}.findFirst,`,
      `    findMany: ${entry.namespace}.findMany,`,
      `    insert: ${entry.namespace}.insert,`,
      `    update: ${entry.namespace}.update,`,
      `    updateMany: ${entry.namespace}.updateMany,`,
      `    delete: ${entry.namespace}.deleteOne,`,
      `    count: ${entry.namespace}.count,`,
      "  },",
    ].join("\n")
  );
  const typeExports = modules.map((entry) => `export type * as ${pascalCase(entry.modelName)}Client from "./${entry.fileName}";`);

  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    ...imports,
    "",
    "export const WlbPg = {",
    ...entries,
    "};",
    "",
    ...typeExports,
    "",
  ].join("\n");
}

function tableModules(tables: readonly TableMetadata[]): readonly { modelName: string; clientKey: string; fileName: string; namespace: string }[] {
  return tables.map((table) => ({
    modelName: table.modelName,
    clientKey: table.clientKey,
    fileName: table.clientKey,
    namespace: `${table.clientKey}Client`,
  }));
}
