import type { PgScalarType } from "../types/column.types";
import type { ColumnMetadata, TableMetadata } from "../types/model.types";
import { renderDefault } from "../schema/ddl-fragments";

const METHOD_BY_PG_TYPE: Readonly<Record<Exclude<PgScalarType, "enum">, string>> = {
  boolean: "Boolean",
  smallint: "SmallInt",
  integer: "Integer",
  bigint: "BigInt",
  smallserial: "SmallSerial",
  serial: "Serial",
  bigserial: "BigSerial",
  numeric: "Numeric",
  real: "Real",
  "double precision": "DoublePrecision",
  money: "Money",
  char: "Char",
  varchar: "VarChar",
  text: "Text",
  bytea: "Bytea",
  uuid: "Uuid",
  json: "Json",
  jsonb: "Jsonb",
  date: "Date",
  time: "Time",
  timetz: "TimeTz",
  timestamp: "Timestamp",
  timestamptz: "TimestampTz",
  interval: "Interval",
  inet: "Inet",
  cidr: "Cidr",
  macaddr: "MacAddr",
  macaddr8: "MacAddr8",
  tsvector: "TsVector",
  tsquery: "TsQuery",
  xml: "Xml",
  bit: "Bit",
  varbit: "VarBit",
  point: "Point",
  line: "Line",
  lseg: "Lseg",
  box: "Box",
  path: "Path",
  polygon: "Polygon",
  circle: "Circle",
  int4range: "Int4Range",
  int8range: "Int8Range",
  numrange: "NumRange",
  tsrange: "TsRange",
  tstzrange: "TstzRange",
  daterange: "DateRange",
  int4multirange: "Int4MultiRange",
  int8multirange: "Int8MultiRange",
  nummultirange: "NumMultiRange",
  tsmultirange: "TsMultiRange",
  tstzmultirange: "TstzMultiRange",
  datemultirange: "DateMultiRange",
};

function renderOptions(column: ColumnMetadata): string {
  const parts: string[] = [];
  if (column.nullable) parts.push("nullable: true");
  if (column.default !== undefined) {
    parts.push(`default: ${JSON.stringify(renderDefault(column.default))} /* raw SQL */`);
  }
  if (column.unique) parts.push("unique: true");
  if (column.primaryKey) parts.push("primaryKey: true");
  if (column.identity) parts.push("identity: true");
  if (column.comment !== undefined) parts.push(`comment: ${JSON.stringify(column.comment)}`);
  return parts.length === 0 ? "" : `{ ${parts.join(", ")} }`;
}

function renderColumnExpression(column: ColumnMetadata): string {
  const options = renderOptions(column);
  const isArray = column.sqlType.endsWith("[]");

  if (column.pgType === "enum" && column.enum !== undefined) {
    const values = JSON.stringify(column.enum.values);
    return `PgTypes.Enum(${JSON.stringify(column.enum.name)}, ${values}${options === "" ? "" : `, ${options}`})`;
  }

  const method = METHOD_BY_PG_TYPE[column.pgType as Exclude<PgScalarType, "enum">] ?? "Text";
  const call = `PgTypes.${method}(${options})`;
  return isArray ? `PgTypes.Array(${call})` : call;
}

/** Generates `generated/models/<Model>.ts`: a read-only, human-readable `PgTypes`-based mirror of one introspected table. Not imported or consumed by anything — reference/documentation only. */
export function generateModelMirrorSource(table: TableMetadata): string {
  const fields = table.columns.map((column) =>
    `  // ${column.sqlType}\n  ${column.fieldName}: ${renderColumnExpression(column)},`
  );
  return [
    `/* Generated by @warbler/database. Read-only mirror of the live "${table.tableName}" table. Do not edit by hand. */`,
    'import { PgTypes } from "@warbler/database";',
    "",
    `export const ${table.modelName}Model = {`,
    ...fields,
    "};",
    "",
  ].join("\n");
}
