import type { DatabaseProjectConfig } from "../types/config.types";

function relativeConfigImport(config: DatabaseProjectConfig): string {
  const depth = config.migrations.generated.split("/").filter((segment) => segment.length > 0).length + 1; // + "runtime"
  return `${"../".repeat(depth)}src/config/database.config`;
}

/** Generates `runtime/pg-factory.ts`: lazy access to the configured Bun `SQL` connection. */
export function generateRuntimeFactorySource(config: DatabaseProjectConfig): string {
  const configImport = relativeConfigImport(config);
  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    'import { createPgConnection } from "@warbler/database";',
    'import type { SQL } from "bun";',
    `import { databaseConfig } from ${JSON.stringify(configImport)};`,
    "",
    "let instance: SQL | undefined;",
    "",
    "export function getPg(): SQL {",
    "  instance ??= createPgConnection(databaseConfig.pg.connection, databaseConfig.pg.log === true);",
    "  return instance;",
    "}",
    "",
  ].join("\n");
}

/** Generates `runtime/pg-client.ts`: the one place the default live Bun `SQL` connection is exposed. */
export function generateRuntimeClientSource(_config: DatabaseProjectConfig): string {
  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    'import { getPg } from "./pg-factory";',
    "",
    "export const pg = getPg();",
    "",
  ].join("\n");
}
