import { DatabaseCompileError } from "../errors";
import type { ColumnMetadata, TableMetadata } from "../types/model.types";

const SERIAL_TYPES = new Set(["smallserial", "serial", "bigserial"]);
const NUMBER_TYPES = new Set(["smallint", "integer", "smallserial", "serial", "real", "double precision"]);
const STRING_NUMBER_TYPES = new Set(["bigint", "bigserial", "numeric", "money"]);
const DATE_TYPES = new Set(["date", "timestamp", "timestamptz"]);
const SUM_AVG_TYPES = new Set([...NUMBER_TYPES, ...STRING_NUMBER_TYPES]);
const FLOAT_TYPES = new Set(["real", "double precision"]);
const INTEGER_SUM_TYPES = new Set(["smallint", "integer", "smallserial", "serial"]);
const COMPARABLE_TYPES = new Set([
  ...SUM_AVG_TYPES,
  "char",
  "varchar",
  "text",
  "uuid",
  "date",
  "time",
  "timetz",
  "timestamp",
  "timestamptz",
  "interval",
  "enum",
  "inet",
  "cidr",
  "macaddr",
  "macaddr8",
  "bit",
  "varbit",
]);

function isAutoGenerated(column: ColumnMetadata): boolean {
  return column.identity || SERIAL_TYPES.has(column.pgType);
}

function isOptionalForInsert(column: ColumnMetadata): boolean {
  return column.nullable || column.default !== undefined || isAutoGenerated(column);
}

function baseTsType(column: ColumnMetadata): string {
  switch (column.pgType) {
    case "boolean":
      return "boolean";
    case "smallint":
    case "integer":
    case "smallserial":
    case "serial":
    case "real":
    case "double precision":
      return "number";
    case "bigint":
    case "bigserial":
    case "numeric":
    case "money":
      return "string";
    case "bytea":
      return "Uint8Array";
    case "json":
    case "jsonb":
      return "unknown";
    case "date":
    case "timestamp":
    case "timestamptz":
      return "Date";
    default:
      return "string";
  }
}

function tsType(column: ColumnMetadata): string {
  const base = baseTsType(column);
  const shape = column.sqlType.endsWith("[]") ? `readonly ${base}[]` : base;
  return column.nullable ? `${shape} | null` : shape;
}

function nonNullableTsType(column: ColumnMetadata): string {
  const base = baseTsType(column);
  return column.sqlType.endsWith("[]") ? `readonly ${base}[]` : base;
}

function pascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function lowerFirst(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function pluralize(name: string): string {
  if (/(?:s|x|z|ch|sh)$/iu.test(name)) return `${name}es`;
  if (/[^aeiou]y$/iu.test(name)) return `${name.slice(0, -1)}ies`;
  return `${name}s`;
}

function filterType(column: ColumnMetadata): string {
  const value = `${pascalCase(column.fieldName)}Value`;
  if (column.pgType === "boolean" || column.pgType === "bytea" || column.pgType === "json" || column.pgType === "jsonb") {
    return `${value} | EqualityFilter<${value}>`;
  }
  if (NUMBER_TYPES.has(column.pgType) || STRING_NUMBER_TYPES.has(column.pgType) || DATE_TYPES.has(column.pgType)) {
    return `${value} | ComparableFilter<${value}>`;
  }
  return `${value} | StringFilter<${value}>`;
}

function isArrayColumn(column: ColumnMetadata): boolean {
  return column.sqlType.endsWith("[]");
}

function supportsSumAvg(column: ColumnMetadata): boolean {
  return !isArrayColumn(column) && SUM_AVG_TYPES.has(column.pgType);
}

function supportsMinMax(column: ColumnMetadata): boolean {
  return !isArrayColumn(column) && COMPARABLE_TYPES.has(column.pgType);
}

function aggregateCapabilities(column: ColumnMetadata): string {
  return `Object.freeze({ count: true, sum: ${supportsSumAvg(column)}, avg: ${supportsSumAvg(column)}, min: ${supportsMinMax(column)}, max: ${supportsMinMax(column)} })`;
}

function sumTsType(column: ColumnMetadata): string {
  if (FLOAT_TYPES.has(column.pgType)) return "number | null";
  if (INTEGER_SUM_TYPES.has(column.pgType) || STRING_NUMBER_TYPES.has(column.pgType)) return "string | null";
  return `${nonNullableTsType(column)} | null`;
}

function avgTsType(column: ColumnMetadata): string {
  if (FLOAT_TYPES.has(column.pgType)) return "number | null";
  if (SUM_AVG_TYPES.has(column.pgType)) return "string | null";
  return `${nonNullableTsType(column)} | null`;
}

function aggregateResultTsType(column: ColumnMetadata, operation: "sum" | "avg" | "min" | "max"): string {
  if (operation === "sum") return sumTsType(column);
  if (operation === "avg") return avgTsType(column);
  return `${nonNullableTsType(column)} | null`;
}

function aggregateComparisonTsType(column: ColumnMetadata, operation: "sum" | "avg" | "min" | "max"): string {
  const result = aggregateResultTsType(column, operation);
  const scalar = nonNullableTsType(column);
  return result.includes(scalar) ? result : `${result} | ${scalar}`;
}

function runtimeKind(column: ColumnMetadata): "string" | "number" | "boolean" | "date" | "bytes" | "json" {
  if (column.pgType === "boolean") return "boolean";
  if (NUMBER_TYPES.has(column.pgType) || STRING_NUMBER_TYPES.has(column.pgType)) return "number";
  if (DATE_TYPES.has(column.pgType)) return "date";
  if (column.pgType === "bytea") return "bytes";
  if (column.pgType === "json" || column.pgType === "jsonb") return "json";
  return "string";
}

function relationFieldName(base: string, used: Set<string>): string {
  let candidate = base;
  let suffix = 2;
  while (used.has(candidate)) candidate = `${base}${suffix++}`;
  used.add(candidate);
  return candidate;
}

function relationBaseName(source: TableMetadata, target: TableMetadata, kind: "one" | "many"): string {
  if (kind === "one") return target.clientKey;
  if (source.modelName.startsWith(target.modelName) && source.modelName.length > target.modelName.length) {
    return pluralize(lowerFirst(source.modelName.slice(target.modelName.length)));
  }
  return pluralize(source.clientKey);
}

interface GeneratedRelation {
  readonly field: string;
  readonly kind: "one" | "many";
  readonly target: TableMetadata;
  readonly localColumn: string;
  readonly foreignColumn: string;
}

function relationsFor(table: TableMetadata, allTables: readonly TableMetadata[]): readonly GeneratedRelation[] {
  const relations: GeneratedRelation[] = [];
  const used = new Set(table.columns.map((column) => column.fieldName));
  for (const fk of table.foreignKeys) {
    const target = allTables.find((candidate) => candidate.tableName === fk.referencesTable);
    if (target === undefined) continue;
    relations.push(Object.freeze({
      field: relationFieldName(relationBaseName(table, target, "one"), used),
      kind: "one",
      target,
      localColumn: fk.column,
      foreignColumn: fk.referencesColumn,
    }));
  }
  for (const source of allTables) {
    for (const fk of source.foreignKeys) {
      if (fk.referencesTable !== table.tableName) continue;
      relations.push(Object.freeze({
        field: relationFieldName(relationBaseName(source, table, "many"), used),
        kind: "many",
        target: source,
        localColumn: fk.referencesColumn,
        foreignColumn: fk.column,
      }));
    }
  }
  return Object.freeze(relations);
}

function rowInterface(table: TableMetadata, typeName: string): string {
  return [`export interface ${typeName} {`, ...table.columns.map((column) => `  ${column.fieldName}: ${tsType(column)};`), "}"].join("\n");
}

function insertInterface(typeName: string, insertable: readonly ColumnMetadata[]): string {
  return [`export interface ${typeName} {`, ...insertable.map((column) => `  ${column.fieldName}${isOptionalForInsert(column) ? "?" : ""}: ${tsType(column)};`), "}"].join("\n");
}

function updateValueType(column: ColumnMetadata): string {
  const value = tsType(column);
  const set = `{ readonly set: ${value}; }`;
  if (NUMBER_TYPES.has(column.pgType) || STRING_NUMBER_TYPES.has(column.pgType)) {
    return `${value} | ${set} | { readonly increment: ${value}; } | { readonly decrement: ${value}; } | { readonly multiply: ${value}; } | { readonly divide: ${value}; }`;
  }
  return `${value} | ${set}`;
}

function updateInterface(typeName: string, updatable: readonly ColumnMetadata[]): string {
  return [`export interface ${typeName} {`, ...updatable.map((column) => `  ${column.fieldName}?: ${updateValueType(column)};`), "}"].join("\n");
}

function valueAliases(columns: readonly ColumnMetadata[]): string {
  return columns.map((column) => `type ${pascalCase(column.fieldName)}Value = ${tsType(column)};`).join("\n");
}

function whereInterface(table: TableMetadata, typeName: string, relations: readonly GeneratedRelation[]): string {
  const fields = table.columns.map((column) => `  readonly ${column.fieldName}?: ${filterType(column)};`);
  const relationFilters = relations.map((relation) => relation.kind === "many"
    ? `  readonly ${relation.field}?: { readonly some?: ${relation.target.modelName}Where; readonly none?: ${relation.target.modelName}Where; readonly every?: ${relation.target.modelName}Where; };`
    : `  readonly ${relation.field}?: { readonly is?: ${relation.target.modelName}Where; readonly isNot?: ${relation.target.modelName}Where; };`);
  return [
    `export interface ${typeName} {`,
    ...fields,
    ...relationFilters,
    `  readonly AND?: ${typeName} | readonly ${typeName}[];`,
    `  readonly OR?: readonly ${typeName}[];`,
    `  readonly NOT?: ${typeName} | readonly ${typeName}[];`,
    "}",
  ].join("\n");
}

function uniqueWhereType(typeName: string, uniqueColumns: readonly ColumnMetadata[]): string {
  return [`export type ${typeName} =`, ...uniqueColumns.map((column) => {
    const others = uniqueColumns.filter((other) => other.fieldName !== column.fieldName).map((other) => ` readonly ${other.fieldName}?: never;`).join("");
    return `  | ({ readonly ${column.fieldName}: ${tsType(column)};${others} })`;
  })].join("\n") + ";";
}

function cursorType(typeName: string, columns: readonly ColumnMetadata[]): string {
  return [`export interface ${typeName} {`, ...columns.map((column) => `  readonly ${column.fieldName}?: ${nonNullableTsType(column)};`), "}"].join("\n");
}

function orderByType(typeName: string, columns: readonly ColumnMetadata[]): string {
  return [`export interface ${typeName} {`, ...columns.map((column) => `  readonly ${column.fieldName}?: SortDirection;`), "}"].join("\n");
}

function scalarFieldUnion(table: TableMetadata): string {
  return `export type ${table.modelName}ScalarField = ${table.columns.map((column) => JSON.stringify(column.fieldName)).join(" | ")};`;
}

function countAggregateInput(table: TableMetadata): string {
  return [
    `export interface ${table.modelName}CountAggregateInput {`,
    "  readonly _all?: boolean;",
    ...table.columns.map((column) => `  readonly ${column.fieldName}?: boolean;`),
    "}",
  ].join("\n");
}

function aggregateInput(table: TableMetadata, typeName: string, columns: readonly ColumnMetadata[]): string {
  return [`export interface ${typeName} {`, ...columns.map((column) => `  readonly ${column.fieldName}?: boolean;`), "}"].join("\n");
}

function aggregatePayload(typeName: string, inputType: string, columns: readonly ColumnMetadata[], operation: "sum" | "avg" | "min" | "max"): string {
  const fields = columns.map((column) => `  & (S extends { readonly ${column.fieldName}: true } ? { readonly ${column.fieldName}: ${aggregateResultTsType(column, operation)} } : {})`);
  return [`export type ${typeName}<S extends ${inputType}> = {}`, ...fields, ";"].join("\n");
}

function countAggregatePayload(table: TableMetadata): string {
  return [
    `export type ${table.modelName}CountAggregatePayload<S extends ${table.modelName}CountAggregateInput> = {}`,
    "  & (S extends { readonly _all: true } ? { readonly _all: number } : {})",
    ...table.columns.map((column) => `  & (S extends { readonly ${column.fieldName}: true } ? { readonly ${column.fieldName}: number } : {})`),
    ";",
  ].join("\n");
}

function aggregateArgs(table: TableMetadata): string {
  return `export interface ${table.modelName}AggregateArgs {
  readonly where?: ${table.modelName}Where;
  readonly _count?: true | ${table.modelName}CountAggregateInput;
  readonly _sum?: ${table.modelName}SumAggregateInput;
  readonly _avg?: ${table.modelName}AvgAggregateInput;
  readonly _min?: ${table.modelName}MinAggregateInput;
  readonly _max?: ${table.modelName}MaxAggregateInput;
}`;
}

function aggregateArgsFields(table: TableMetadata): readonly string[] {
  return [
    `  & (A extends { readonly _count: infer S } ? S extends true ? { readonly _count: number } : S extends ${table.modelName}CountAggregateInput ? { readonly _count: ${table.modelName}CountAggregatePayload<S> } : {} : {})`,
    `  & (A extends { readonly _sum: infer S extends ${table.modelName}SumAggregateInput } ? { readonly _sum: ${table.modelName}SumAggregatePayload<S> } : {})`,
    `  & (A extends { readonly _avg: infer S extends ${table.modelName}AvgAggregateInput } ? { readonly _avg: ${table.modelName}AvgAggregatePayload<S> } : {})`,
    `  & (A extends { readonly _min: infer S extends ${table.modelName}MinAggregateInput } ? { readonly _min: ${table.modelName}MinAggregatePayload<S> } : {})`,
    `  & (A extends { readonly _max: infer S extends ${table.modelName}MaxAggregateInput } ? { readonly _max: ${table.modelName}MaxAggregatePayload<S> } : {})`,
  ];
}

function aggregateResultPayload(table: TableMetadata): string {
  return [`export type ${table.modelName}AggregatePayload<A extends ${table.modelName}AggregateArgs> = {}`, ...aggregateArgsFields(table), ";"].join("\n");
}

function aggregateFilterType(table: TableMetadata): string {
  return `export type ${table.modelName}AggregateFilter<T> = ComparableFilter<T>;`;
}

function havingType(table: TableMetadata): string {
  const fields = table.columns.map((column) => {
    const operations: string[] = [`    readonly _count?: ${table.modelName}AggregateFilter<number>;`];
    if (supportsSumAvg(column)) {
      operations.push(`    readonly _sum?: ${table.modelName}AggregateFilter<${aggregateComparisonTsType(column, "sum")}>;`);
      operations.push(`    readonly _avg?: ${table.modelName}AggregateFilter<${aggregateComparisonTsType(column, "avg")}>;`);
    }
    if (supportsMinMax(column)) {
      operations.push(`    readonly _min?: ${table.modelName}AggregateFilter<${aggregateComparisonTsType(column, "min")}>;`);
      operations.push(`    readonly _max?: ${table.modelName}AggregateFilter<${aggregateComparisonTsType(column, "max")}>;`);
    }
    return [`  readonly ${column.fieldName}?: {`, ...operations, "  };"].join("\n");
  });
  return [`export interface ${table.modelName}GroupByHaving {`, ...fields, "}"].join("\n");
}

function aggregateOrderByInput(table: TableMetadata, typeName: string, columns: readonly ColumnMetadata[], includeAll = false): string {
  return [
    `export interface ${typeName} {`,
    ...(includeAll ? ["  readonly _all?: SortDirection;"] : []),
    ...columns.map((column) => `  readonly ${column.fieldName}?: SortDirection;`),
    "}",
  ].join("\n");
}

function groupByOrderByType(table: TableMetadata): string {
  return [
    `export interface ${table.modelName}GroupByOrderBy {`,
    ...table.columns.map((column) => `  readonly ${column.fieldName}?: SortDirection;`),
    `  readonly _count?: ${table.modelName}CountOrderByAggregateInput;`,
    `  readonly _sum?: ${table.modelName}SumOrderByAggregateInput;`,
    `  readonly _avg?: ${table.modelName}AvgOrderByAggregateInput;`,
    `  readonly _min?: ${table.modelName}MinOrderByAggregateInput;`,
    `  readonly _max?: ${table.modelName}MaxOrderByAggregateInput;`,
    "}",
  ].join("\n");
}

function groupByArgs(table: TableMetadata): string {
  return `export interface ${table.modelName}GroupByArgs extends ${table.modelName}AggregateArgs {
  readonly by: readonly ${table.modelName}ScalarField[];
  readonly having?: ${table.modelName}GroupByHaving;
  readonly orderBy?: ${table.modelName}GroupByOrderBy | readonly ${table.modelName}GroupByOrderBy[];
  readonly take?: number;
  readonly skip?: number;
}`;
}

function groupByPayload(table: TableMetadata): string {
  return `export type ${table.modelName}GroupByPayload<A extends ${table.modelName}GroupByArgs> = {
  readonly [K in A["by"][number]]: ${table.modelName}Row[K];
} & ${table.modelName}AggregatePayload<A>;`;
}

function selectType(table: TableMetadata, typeName: string, relations: readonly GeneratedRelation[]): string {
  return [
    `export interface ${typeName} {`,
    ...table.columns.map((column) => `  readonly ${column.fieldName}?: boolean;`),
    ...relations.map((relation) => `  readonly ${relation.field}?: boolean | ${relation.target.modelName}RelationArgs;`),
    "}",
  ].join("\n");
}

function includeType(typeName: string, relations: readonly GeneratedRelation[]): string {
  return [`export interface ${typeName} {`, ...relations.map((relation) => `  readonly ${relation.field}?: boolean | ${relation.target.modelName}RelationArgs;`), "}"].join("\n");
}

function selectPayloadType(table: TableMetadata, rowType: string, relations: readonly GeneratedRelation[]): string {
  const scalar = table.columns.map((column) => `  & (S extends { readonly ${column.fieldName}: true } ? { readonly ${column.fieldName}: ${rowType}["${column.fieldName}"] } : {})`);
  const relation = relations.map((item) => {
    const nested = `${item.target.modelName}RelationPayload<NonNullable<S["${item.field}"]>>`;
    return `  & (S extends { readonly ${item.field}: infer R } ? (R extends false | undefined ? {} : { readonly ${item.field}: ${item.kind === "many" ? `readonly ${nested}[]` : `${nested} | null`} }) : {})`;
  });
  return [`export type ${table.modelName}SelectPayload<S extends ${table.modelName}Select> =`, ...scalar, ...relation, ";"].join("\n");
}

function includePayloadType(table: TableMetadata, rowType: string, relations: readonly GeneratedRelation[]): string {
  const relation = relations.map((item) => {
    const nested = `${item.target.modelName}RelationPayload<NonNullable<I["${item.field}"]>>`;
    return `  & (I extends { readonly ${item.field}: infer R } ? (R extends false | undefined ? {} : { readonly ${item.field}: ${item.kind === "many" ? `readonly ${nested}[]` : `${nested} | null`} }) : {})`;
  });
  return [`export type ${table.modelName}IncludePayload<I extends ${table.modelName}Include> = ${rowType}`, ...relation, ";"].join("\n");
}

function runtimeModelSource(table: TableMetadata, allTables: readonly TableMetadata[]): string {
  const columns = table.columns.map((column) =>
    `{ field: ${JSON.stringify(column.fieldName)}, column: ${JSON.stringify(column.columnName)}, kind: ${JSON.stringify(runtimeKind(column))}, pgType: ${JSON.stringify(column.pgType)}, nullable: ${column.nullable}, unique: ${column.unique}, primaryKey: ${column.primaryKey}, aggregate: ${aggregateCapabilities(column)} }`
  );
  const relations = relationsFor(table, allTables).map((relation) =>
    `{ field: ${JSON.stringify(relation.field)}, kind: ${JSON.stringify(relation.kind)}, target: ${JSON.stringify(relation.target.modelName)}, localColumn: ${JSON.stringify(relation.localColumn)}, foreignColumn: ${JSON.stringify(relation.foreignColumn)} }`
  );
  return `${JSON.stringify(table.modelName)}: {
      name: ${JSON.stringify(table.modelName)},
      table: ${JSON.stringify(table.tableName)},
      defaultOrderColumn: ${JSON.stringify(table.primaryKey[0] ?? table.columns[0]?.columnName ?? "")},
      primaryKeyFields: Object.freeze([${table.primaryKey.map((columnName) => {
        const column = table.columns.find((candidate) => candidate.columnName === columnName);
        return JSON.stringify(column?.fieldName ?? columnName);
      }).join(", ")}]),
      columns: Object.freeze([${columns.join(", ")}]),
      relations: Object.freeze([${relations.join(", ")}]),
    }`;
}

function runtimeSchemaSource(allTables: readonly TableMetadata[]): string {
  return [
    "const READ_SCHEMA = Object.freeze({",
    "  models: Object.freeze({",
    ...allTables.map((table) => `    ${runtimeModelSource(table, allTables)},`),
    "  }),",
    "}) as RuntimeReadSchema;",
  ].join("\n");
}

function delegateInterface(table: TableMetadata, rowType: string): string {
  return `export interface ${table.modelName}Delegate {
  findUnique<S extends ${table.modelName}Select>(args: { readonly where: ${table.modelName}UniqueWhere; readonly select: S; readonly include?: never }): Promise<${table.modelName}SelectPayload<S> | null>;
  findUnique<I extends ${table.modelName}Include>(args: { readonly where: ${table.modelName}UniqueWhere; readonly select?: never; readonly include: I }): Promise<${table.modelName}IncludePayload<I> | null>;
  findUnique(args: { readonly where: ${table.modelName}UniqueWhere }): Promise<${rowType} | null>;
  findUniqueOrThrow<S extends ${table.modelName}Select>(args: { readonly where: ${table.modelName}UniqueWhere; readonly select: S; readonly include?: never }): Promise<${table.modelName}SelectPayload<S>>;
  findUniqueOrThrow<I extends ${table.modelName}Include>(args: { readonly where: ${table.modelName}UniqueWhere; readonly select?: never; readonly include: I }): Promise<${table.modelName}IncludePayload<I>>;
  findUniqueOrThrow(args: { readonly where: ${table.modelName}UniqueWhere }): Promise<${rowType}>;
  findFirst<S extends ${table.modelName}Select>(args: Omit<${table.modelName}FindFirstArgs<S, undefined>, "select" | "include"> & { readonly select: S; readonly include?: never }): Promise<${table.modelName}SelectPayload<S> | null>;
  findFirst<I extends ${table.modelName}Include>(args: Omit<${table.modelName}FindFirstArgs<undefined, I>, "select" | "include"> & { readonly select?: never; readonly include: I }): Promise<${table.modelName}IncludePayload<I> | null>;
  findFirst(args?: Omit<${table.modelName}FindFirstArgs, "select" | "include">): Promise<${rowType} | null>;
  findFirstOrThrow<S extends ${table.modelName}Select>(args: Omit<${table.modelName}FindFirstArgs<S, undefined>, "select" | "include"> & { readonly select: S; readonly include?: never }): Promise<${table.modelName}SelectPayload<S>>;
  findFirstOrThrow<I extends ${table.modelName}Include>(args: Omit<${table.modelName}FindFirstArgs<undefined, I>, "select" | "include"> & { readonly select?: never; readonly include: I }): Promise<${table.modelName}IncludePayload<I>>;
  findFirstOrThrow(args?: Omit<${table.modelName}FindFirstArgs, "select" | "include">): Promise<${rowType}>;
  findMany<S extends ${table.modelName}Select>(args: Omit<${table.modelName}FindManyArgs<S, undefined>, "select" | "include"> & { readonly select: S; readonly include?: never }): Promise<readonly ${table.modelName}SelectPayload<S>[]>;
  findMany<I extends ${table.modelName}Include>(args: Omit<${table.modelName}FindManyArgs<undefined, I>, "select" | "include"> & { readonly select?: never; readonly include: I }): Promise<readonly ${table.modelName}IncludePayload<I>[]>;
  findMany(args?: Omit<${table.modelName}FindManyArgs, "select" | "include">): Promise<readonly ${rowType}[]>;
  create<S extends ${table.modelName}Select>(args: { readonly data: ${table.modelName}CreateInput; readonly select: S }): Promise<${table.modelName}SelectPayload<S>>;
  create(args: { readonly data: ${table.modelName}CreateInput }): Promise<${rowType}>;
  insert(data: ${table.modelName}CreateInput): Promise<${rowType}>;
  createMany(args: { readonly data: readonly ${table.modelName}CreateInput[]; readonly skipDuplicates?: boolean }): Promise<MutationCountResult>;
  createManyAndReturn<S extends ${table.modelName}Select>(args: { readonly data: readonly ${table.modelName}CreateInput[]; readonly skipDuplicates?: boolean; readonly select: S }): Promise<readonly ${table.modelName}SelectPayload<S>[]>;
  createManyAndReturn(args: { readonly data: readonly ${table.modelName}CreateInput[]; readonly skipDuplicates?: boolean }): Promise<readonly ${rowType}[]>;
  update<S extends ${table.modelName}Select>(args: { readonly where: ${table.modelName}UniqueWhere; readonly data: ${table.modelName}UpdateInput; readonly select: S }): Promise<${table.modelName}SelectPayload<S>>;
  update(args: { readonly where: ${table.modelName}UniqueWhere; readonly data: ${table.modelName}UpdateInput }): Promise<${rowType}>;
  updateMany(args: { readonly where: ${table.modelName}Where; readonly data: ${table.modelName}UpdateManyInput }): Promise<MutationCountResult>;
  updateManyAndReturn<S extends ${table.modelName}Select>(args: { readonly where: ${table.modelName}Where; readonly data: ${table.modelName}UpdateManyInput; readonly select: S }): Promise<readonly ${table.modelName}SelectPayload<S>[]>;
  updateManyAndReturn(args: { readonly where: ${table.modelName}Where; readonly data: ${table.modelName}UpdateManyInput }): Promise<readonly ${rowType}[]>;
  upsert<S extends ${table.modelName}Select>(args: { readonly where: ${table.modelName}UniqueWhere; readonly create: ${table.modelName}CreateInput; readonly update: ${table.modelName}UpdateInput; readonly select: S }): Promise<${table.modelName}SelectPayload<S>>;
  upsert(args: { readonly where: ${table.modelName}UniqueWhere; readonly create: ${table.modelName}CreateInput; readonly update: ${table.modelName}UpdateInput }): Promise<${rowType}>;
  delete<S extends ${table.modelName}Select>(args: { readonly where: ${table.modelName}UniqueWhere; readonly select: S }): Promise<${table.modelName}SelectPayload<S>>;
  delete(args: { readonly where: ${table.modelName}UniqueWhere }): Promise<${rowType}>;
  deleteMany(args: { readonly where: ${table.modelName}Where }): Promise<MutationCountResult>;
  count(): Promise<number>;
  count(args: { readonly where?: ${table.modelName}Where }): Promise<number>;
  count<S extends ${table.modelName}CountAggregateInput>(args: { readonly where?: ${table.modelName}Where; readonly select: S }): Promise<${table.modelName}CountAggregatePayload<S>>;
  exists(args?: { readonly where?: ${table.modelName}Where }): Promise<boolean>;
  aggregate<A extends ${table.modelName}AggregateArgs>(args: A): Promise<${table.modelName}AggregatePayload<A>>;
  groupBy<A extends ${table.modelName}GroupByArgs>(args: A): Promise<readonly ${table.modelName}GroupByPayload<A>[]>;
}`;
}

function delegateFactory(table: TableMetadata): string {
  return `export function create${table.modelName}Delegate(database: SQL): ${table.modelName}Delegate {
  const delegate: Record<string, unknown> = {};
  delegate.findUnique = (args: ${table.modelName}FindUniqueArgs) => executeFindUnique(database, READ_SCHEMA, MODEL, args);
  delegate.findUniqueOrThrow = (args: ${table.modelName}FindUniqueArgs) => executeFindUniqueOrThrow(database, READ_SCHEMA, MODEL, args);
  delegate.findFirst = (args?: ${table.modelName}FindFirstArgs) => executeFindFirst(database, READ_SCHEMA, MODEL, args);
  delegate.findFirstOrThrow = (args?: ${table.modelName}FindFirstArgs) => executeFindFirstOrThrow(database, READ_SCHEMA, MODEL, args);
  delegate.findMany = (args?: ${table.modelName}FindManyArgs) => executeFindMany(database, READ_SCHEMA, MODEL, args);
  delegate.create = (args: { readonly data: ${table.modelName}CreateInput; readonly select?: ${table.modelName}Select }) => executeCreate(database, READ_SCHEMA, MODEL, args);
  delegate.insert = (data: ${table.modelName}CreateInput) => executeCreate(database, READ_SCHEMA, MODEL, { data });
  delegate.createMany = (args: { readonly data: readonly ${table.modelName}CreateInput[]; readonly skipDuplicates?: boolean }) => executeCreateMany(database, READ_SCHEMA, MODEL, args);
  delegate.createManyAndReturn = (args: { readonly data: readonly ${table.modelName}CreateInput[]; readonly skipDuplicates?: boolean; readonly select?: ${table.modelName}Select }) => executeCreateManyAndReturn(database, READ_SCHEMA, MODEL, args);
  delegate.update = (args: { readonly where: ${table.modelName}UniqueWhere; readonly data: ${table.modelName}UpdateInput; readonly select?: ${table.modelName}Select }) => executeUpdate(database, READ_SCHEMA, MODEL, args);
  delegate.updateMany = (args: { readonly where: ${table.modelName}Where; readonly data: ${table.modelName}UpdateManyInput }) => executeUpdateMany(database, READ_SCHEMA, MODEL, args);
  delegate.updateManyAndReturn = (args: { readonly where: ${table.modelName}Where; readonly data: ${table.modelName}UpdateManyInput; readonly select?: ${table.modelName}Select }) => executeUpdateManyAndReturn(database, READ_SCHEMA, MODEL, args);
  delegate.upsert = (args: { readonly where: ${table.modelName}UniqueWhere; readonly create: ${table.modelName}CreateInput; readonly update: ${table.modelName}UpdateInput; readonly select?: ${table.modelName}Select }) => executeUpsert(database, READ_SCHEMA, MODEL, args);
  delegate.delete = (args: { readonly where: ${table.modelName}UniqueWhere; readonly select?: ${table.modelName}Select }) => executeDelete(database, READ_SCHEMA, MODEL, args);
  delegate.deleteMany = (args: { readonly where: ${table.modelName}Where }) => executeDeleteMany(database, READ_SCHEMA, MODEL, args);
  delegate.count = (args?: { readonly where?: ${table.modelName}Where; readonly select?: ${table.modelName}CountAggregateInput }) => executeCount(database, READ_SCHEMA, MODEL, args);
  delegate.exists = (args?: { readonly where?: ${table.modelName}Where }) => executeExists(database, READ_SCHEMA, MODEL, args);
  delegate.aggregate = (args: ${table.modelName}AggregateArgs) => executeAggregate(database, READ_SCHEMA, MODEL, args);
  delegate.groupBy = (args: ${table.modelName}GroupByArgs) => executeGroupBy(database, READ_SCHEMA, MODEL, args);
  Object.freeze(delegate);
  return delegate as unknown as ${table.modelName}Delegate;
}`;
}

function defaultExports(table: TableMetadata): readonly string[] {
  return [
    `const DEFAULT_DELEGATE = create${table.modelName}Delegate(pg);`,
    "export const findUnique = DEFAULT_DELEGATE.findUnique;",
    "export const findUniqueOrThrow = DEFAULT_DELEGATE.findUniqueOrThrow;",
    "export const findFirst = DEFAULT_DELEGATE.findFirst;",
    "export const findFirstOrThrow = DEFAULT_DELEGATE.findFirstOrThrow;",
    "export const findMany = DEFAULT_DELEGATE.findMany;",
    "export const create = DEFAULT_DELEGATE.create;",
    "export const insert = DEFAULT_DELEGATE.insert;",
    "export const createMany = DEFAULT_DELEGATE.createMany;",
    "export const createManyAndReturn = DEFAULT_DELEGATE.createManyAndReturn;",
    "export const update = DEFAULT_DELEGATE.update;",
    "export const updateMany = DEFAULT_DELEGATE.updateMany;",
    "export const updateManyAndReturn = DEFAULT_DELEGATE.updateManyAndReturn;",
    "export const upsert = DEFAULT_DELEGATE.upsert;",
    "export const deleteOne = DEFAULT_DELEGATE.delete;",
    "export const deleteMany = DEFAULT_DELEGATE.deleteMany;",
    "export const count = DEFAULT_DELEGATE.count;",
    "export const exists = DEFAULT_DELEGATE.exists;",
    "export const aggregate = DEFAULT_DELEGATE.aggregate;",
    "export const groupBy = DEFAULT_DELEGATE.groupBy;",
  ];
}

function relationImports(table: TableMetadata, relations: readonly GeneratedRelation[]): readonly string[] {
  const targets = [...new Set(relations.map((relation) => relation.target).filter((target) => target.modelName !== table.modelName))];
  return targets.map((target) => `import type { ${target.modelName}Include, ${target.modelName}IncludePayload, ${target.modelName}RelationArgs, ${target.modelName}RelationPayload, ${target.modelName}Select, ${target.modelName}SelectPayload, ${target.modelName}Where } from "./${target.clientKey}";`);
}

/** Generates the CRUD client source for a single model, as plain TypeScript source text. */
export function generateClientSource(table: TableMetadata, allTables: readonly TableMetadata[] = [table]): string {
  const uniqueColumns = table.columns.filter((column) => column.primaryKey || column.unique);
  if (uniqueColumns.length === 0) {
    throw new DatabaseCompileError(table.modelName, "At least one column must be marked `primaryKey` or `unique` to generate findUnique/update/delete.");
  }

  const relations = relationsFor(table, allTables);
  const insertable = table.columns.filter((column) => !isAutoGenerated(column));
  const updatable = insertable.filter((column) => !column.primaryKey);
  const rowType = `${table.modelName}Row`;

  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    'import { executeAggregate, executeCount, executeCreate, executeCreateMany, executeCreateManyAndReturn, executeDelete, executeDeleteMany, executeExists, executeFindFirst, executeFindFirstOrThrow, executeFindMany, executeFindUnique, executeFindUniqueOrThrow, executeGroupBy, executeUpdate, executeUpdateMany, executeUpdateManyAndReturn, executeUpsert } from "@warbler/database";',
    'import type { ComparableFilter, EqualityFilter, MutationCountResult, RuntimeReadSchema, SortDirection, StringFilter } from "@warbler/database";',
    'import type { SQL } from "bun";',
    'import { pg } from "../runtime/pg-client";',
    ...relationImports(table, relations),
    "",
    rowInterface(table, rowType),
    "",
    valueAliases(table.columns),
    "",
    insertInterface(`${table.modelName}CreateInput`, insertable),
    "",
    updateInterface(`${table.modelName}UpdateInput`, updatable),
    "",
    updateInterface(`${table.modelName}UpdateManyInput`, updatable),
    "",
    uniqueWhereType(`${table.modelName}UniqueWhere`, uniqueColumns),
    "",
    cursorType(`${table.modelName}Cursor`, table.columns),
    "",
    whereInterface(table, `${table.modelName}Where`, relations),
    "",
    orderByType(`${table.modelName}OrderBy`, table.columns),
    "",
    scalarFieldUnion(table),
    "",
    countAggregateInput(table),
    "",
    aggregateInput(table, `${table.modelName}SumAggregateInput`, table.columns.filter(supportsSumAvg)),
    "",
    aggregateInput(table, `${table.modelName}AvgAggregateInput`, table.columns.filter(supportsSumAvg)),
    "",
    aggregateInput(table, `${table.modelName}MinAggregateInput`, table.columns.filter(supportsMinMax)),
    "",
    aggregateInput(table, `${table.modelName}MaxAggregateInput`, table.columns.filter(supportsMinMax)),
    "",
    countAggregatePayload(table),
    aggregatePayload(`${table.modelName}SumAggregatePayload`, `${table.modelName}SumAggregateInput`, table.columns.filter(supportsSumAvg), "sum"),
    aggregatePayload(`${table.modelName}AvgAggregatePayload`, `${table.modelName}AvgAggregateInput`, table.columns.filter(supportsSumAvg), "avg"),
    aggregatePayload(`${table.modelName}MinAggregatePayload`, `${table.modelName}MinAggregateInput`, table.columns.filter(supportsMinMax), "min"),
    aggregatePayload(`${table.modelName}MaxAggregatePayload`, `${table.modelName}MaxAggregateInput`, table.columns.filter(supportsMinMax), "max"),
    aggregateArgs(table),
    aggregateResultPayload(table),
    aggregateFilterType(table),
    havingType(table),
    aggregateOrderByInput(table, `${table.modelName}CountOrderByAggregateInput`, table.columns, true),
    aggregateOrderByInput(table, `${table.modelName}SumOrderByAggregateInput`, table.columns.filter(supportsSumAvg)),
    aggregateOrderByInput(table, `${table.modelName}AvgOrderByAggregateInput`, table.columns.filter(supportsSumAvg)),
    aggregateOrderByInput(table, `${table.modelName}MinOrderByAggregateInput`, table.columns.filter(supportsMinMax)),
    aggregateOrderByInput(table, `${table.modelName}MaxOrderByAggregateInput`, table.columns.filter(supportsMinMax)),
    groupByOrderByType(table),
    groupByArgs(table),
    groupByPayload(table),
    "",
    selectType(table, `${table.modelName}Select`, relations),
    "",
    includeType(`${table.modelName}Include`, relations),
    "",
    `export interface ${table.modelName}RelationArgs {
  readonly where?: ${table.modelName}Where;
  readonly select?: ${table.modelName}Select;
  readonly include?: ${table.modelName}Include;
  readonly orderBy?: ${table.modelName}OrderBy | readonly ${table.modelName}OrderBy[];
  readonly take?: number;
  readonly skip?: number;
}`,
    "",
    `export type ${table.modelName}FindUniqueArgs<S extends ${table.modelName}Select | undefined = undefined, I extends ${table.modelName}Include | undefined = undefined> = { readonly where: ${table.modelName}UniqueWhere; readonly select?: S; readonly include?: never; } | { readonly where: ${table.modelName}UniqueWhere; readonly select?: never; readonly include?: I; };`,
    `export type ${table.modelName}FindFirstArgs<S extends ${table.modelName}Select | undefined = undefined, I extends ${table.modelName}Include | undefined = undefined> = { readonly where?: ${table.modelName}Where; readonly select?: S; readonly include?: never; readonly orderBy?: ${table.modelName}OrderBy | readonly ${table.modelName}OrderBy[]; readonly take?: number; readonly skip?: number; readonly cursor?: ${table.modelName}Cursor; } | { readonly where?: ${table.modelName}Where; readonly select?: never; readonly include?: I; readonly orderBy?: ${table.modelName}OrderBy | readonly ${table.modelName}OrderBy[]; readonly take?: number; readonly skip?: number; readonly cursor?: ${table.modelName}Cursor; };`,
    `export type ${table.modelName}FindManyArgs<S extends ${table.modelName}Select | undefined = undefined, I extends ${table.modelName}Include | undefined = undefined> = ${table.modelName}FindFirstArgs<S, I>;`,
    "",
    selectPayloadType(table, rowType, relations),
    includePayloadType(table, rowType, relations),
    `export type ${table.modelName}RelationPayload<A> = A extends { readonly select: infer S extends ${table.modelName}Select } ? ${table.modelName}SelectPayload<S> : A extends { readonly include: infer I extends ${table.modelName}Include } ? ${table.modelName}IncludePayload<I> : ${rowType};`,
    "",
    runtimeSchemaSource(allTables),
    `const MODEL = READ_SCHEMA.models[${JSON.stringify(table.modelName)}]!;`,
    "",
    delegateInterface(table, rowType),
    "",
    delegateFactory(table),
    "",
    ...defaultExports(table),
    "",
  ].join("\n");
}

/** Generates `client/index.ts`: imports every per-model module and assembles `WlbPg`. */
export function generateClientBarrelSource(tables: readonly TableMetadata[]): string {
  const modules = tableModules(tables);
  const imports = modules.map((entry) => `import * as ${entry.namespace} from "./${entry.fileName}";`);
  const delegateFields = modules.map((entry) => `  readonly ${entry.clientKey}: ${entry.namespace}.${entry.modelName}Delegate;`);
  const entries = modules.map((entry) => `    ${entry.clientKey}: ${entry.namespace}.create${entry.modelName}Delegate(database),`);
  const typeExports = modules.map((entry) => `export type * as ${pascalCase(entry.modelName)}Client from "./${entry.fileName}";`);
  return [
    "/* Generated by @warbler/database. Do not edit by hand. */",
    'import { executeTransaction } from "@warbler/database";',
    'import type { TransactionOptions } from "@warbler/database";',
    'import type { SQL, TransactionSQL } from "bun";',
    'import { pg } from "../runtime/pg-client";',
    ...imports,
    "",
    "interface WlbPgDelegates<Database extends SQL> {",
    "  readonly db: Database;",
    ...delegateFields,
    "}",
    "",
    "export type WlbPgTransactionClient = Readonly<WlbPgDelegates<TransactionSQL>>;",
    "export type WlbPgClient = Readonly<WlbPgDelegates<SQL> & {",
    "  readonly transaction: typeof transaction;",
    "}>;",
    "",
    "function createClient<Database extends SQL>(database: Database): Readonly<WlbPgDelegates<Database>> {",
    "  return Object.freeze({",
    "    db: database,",
    ...entries,
    "  });",
    "}",
    "",
    "const CLIENT = createClient(pg);",
    "",
    "export function transaction<Result>(",
    "  callback: (tx: WlbPgTransactionClient) => Result | Promise<Result>,",
    "  options?: TransactionOptions,",
    "): Promise<Awaited<Result>> {",
    "  return executeTransaction(pg, (tx) => callback(createClient(tx)), options);",
    "}",
    "",
    "export const WlbPg: WlbPgClient = Object.freeze({",
    "  ...CLIENT,",
    "  transaction,",
    "});",
    "",
    ...typeExports,
    "",
  ].join("\n");
}

function tableModules(tables: readonly TableMetadata[]): readonly { modelName: string; clientKey: string; fileName: string; namespace: string }[] {
  return tables.map((table) => ({
    modelName: table.modelName,
    clientKey: table.clientKey,
    fileName: table.clientKey,
    namespace: `${table.clientKey}Client`,
  }));
}
