import type { CompiledCatalog } from "./catalog";

/** Emits a deterministic catalog module suitable for production bundling without JSON parsing. */
export function generateCatalogModule(catalog: CompiledCatalog): string {
  const serialized = JSON.stringify(catalog.toJSON(), null, 2);
  return `// Generated by @warbler/i18n. Do not edit.\nimport { CompiledCatalog } from "@warbler/i18n";\n\nexport const catalog = new CompiledCatalog(${serialized} as const);\n`;
}
